### ISSUE TITLE
jasmineReporters.JUnitXmlReporter failed to output one result file some times

### ISSUE THREAD

**Issue by yymycabbage** [larrymyers/jasmine-reporters#111] opened 2015-07-30 15:12 UTC
I'm using protractor with Jasmine, and run our E2E test cases periodically on Jenkins, from the result we often find some test result file are missing (1 file missed in most case).

here is my protractor config:

```
 var timestamp = new Date().getTime().toString();
 var newFolder = "./result/e2e/reports/" + timestamp;
 jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            savePath: newFolder,
            consolidateAll: true
        }));
```

here is an example, the one with 9 items is correct:

![missingfile](https://cloud.githubusercontent.com/assets/7121704/8986748/4d8626f0-3710-11e5-8eae-1a851c94b57c.PNG)

**Comment by active-low** [comment] 2015-08-11 21:38
I have a problem that sounds very similar.  I kick off our E2E tests from Jenkins and then pull the result files into the test results in Jenkins.  The tests suites run in parallel on a selenium grid (```shardTestFiles = true```), result file names have the session id in them, and sometimes a test suite runs but no result file is output.

```javascript
onPrepare: function() {
    return browser.getCapabilities()
        .then(function(capabilities) {
            return {
                browserName: capabilities.caps_.browserName.toUpperCase(),
                browserVersion: capabilities.caps_.version
            };
        })
        .then(function(result) {
            return browser.getSession()
                .then(function(session) {
                    result.sessionId = session.getId();
                    return result;
                });
        })
        .then(function(result) {
            // when test results are missing is the same file name being used twice or is a file not getting created?
            console.log(result.browserName + '-' + result.browserVersion + '#' + result.sessionId);

            jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
                consolidateAll: true,
                filePrefix: result.browserName + '-' + result.browserVersion + '#' + result.sessionId,
                savePath: '../'
            }));
        });
}
```

Up to this point I haven't been able to nail down whether the same file name is being used twice or if the missing files are not generated at all, but my understanding is that because I am returning a promise from onPrepare it should be waiting to run the tests until the reporter is set up.

**Comment by bloveridge** [comment] 2015-09-11 03:36
My suspicion is that, as @gregjhogan suggests, in some cases the same directory name is being used twice (e.g. executed quickly using the same timestamp). You might try incrementing a closure-accessible counter to disambiguate timestamps, sessions, etc. to ensure uniqueness and see if the problem persists.

Closing for now as there isn't enough information to reproduce this and track down a specific bug—current information points to uniqueness or other environmental specifics.

**Closed by bloveridge** 2015-09-11 03:36 UTC

**Comment by gregjhogan** [comment] 2015-09-11 07:22
@bloveridge after reviewing the output from the console.log() call in the onPrepare code I posted previously, I can tell that I am getting unique file names and sometimes a file is not getting created.

For example, here are two files that should have been created from a single run:
CHROME-45.0.2454.85#08b5c635-54a0-4d7b-87e7-5a0e15fc6ec4 - created - took 31.976 seconds
CHROME-45.0.2454.85#c9eeadb6-f32d-4459-9586-c27cfa58c7d9 - missing - took 45.547 seconds

Any ideas how I can investigate this further, or what I could be doing wrong?

**Comment by bloveridge** [comment] 2015-09-11 16:16
Ah, I can see how that makes sense. You should look into the recently-added `modifySuiteName` option to JUnitXmlReporter. This should allow you to change the suite name for each run, thus disambiguating them for Jenkins.
