### ISSUE TITLE
NodeJS attempt: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by Jarlotee** [larrymyers/jasmine-reporters#105] opened 2015-07-10 20:52 UTC
I am using jest-cli 0.4.15 and jasmine-reporters 1.0.2 and am getting the following error:

```
Warning: writing junit report failed for 'output', 'TEST-CheckboxWithLabel.xml'. Reasons:
  Rhino attempt: java is not defined
  PhantomJs attempt: __phantom_writeFile is not defined
  NodeJS attempt: ENOENT, no such file or directory 'D:\Projects\git\carmax.com\output\TEST-CheckboxWithLabel.xml'
```

Using the following configuration
```js

jasmine.VERBOSE = true;

require('jasmine-reporters');

var reporter = new jasmine.JUnitXmlReporter("output");
jasmine.getEnv().addReporter(reporter);

```

If I manually create the output directory it works fine. Looks like there is some bug related to directory creation.

**Comment by bloveridge** [comment] 2015-09-27 21:38
Did you ever figure this out? I agree this looks like an issue creating directories. jasmine-reporters uses node-mkdirp to create directories. Likely the problem is either in this library or with the permissions being used by the process executing jasmine-reporters.

If you haven't already, one thing you could try is updating the version of mkdirp (latest is 0.5.1) -- if such solves your problem, I am happy to update the dependency version. If you have otherwise figured the problem out, I would love to close out this issue.

**Comment by Jarlotee** [comment] 2015-09-28 13:22
@bloveridge I will give it a try and let you know.

**Comment by robwhess** [comment] 2016-01-12 22:16
FWIW, I am having this same problem, and I can confirm that it still happens after manually upgrading the mkdirp dependency to version 0.5.1.  This is just running on my local machine by calling `jest` in my project's root directory.  The errors don't occur if I pre-create the test results output directory.

**Comment by iamtheddrman** [comment] 2016-03-21 17:32
I hit this same issue today. A fix for this would be great. I'll have to commit an output file to persist the directory in git so that I can get my test scripts to run in Jenkins, just so that it can then parse the JUnit output. It would be nice to have the test output folder be transient instead of permanently in our repo.

**Comment by MattFoley** [comment] 2016-06-20 19:39
Actually, in 2.2.0 this is working great, which includes the mkdirp update. mkdirp needed to be updated to remove references to octal literals (and it was in 0.5.1 there, and 2.2.0 here.)

After that update, you need to run Jest with `sudo` so that it can create the directory.

Here is my setup in case anyone else is curious:

setupTestFrameworkScriptFile:
```js
var reporters = require('jasmine-reporters');
var junitReporter = new reporters.JUnitXmlReporter({
    savePath: __dirname +'/output/',
    consolidateAll: true,
    filePrefix: 'xmloutput',
});

var env = jasmine.getEnv();
env.addReporter(junitReporter);
```

Jest package.json configuration:
```json
"jest": {
    "globals": {
      "__DEV__": true
    },
    "setupTestFrameworkScriptFile": "<rootDir>/jestSupport/setup-jasmine-env.js",
    "testPathIgnorePatterns": [
      "/node_modules/",
      "packager/react-packager/src/Activity/"
    ],
    "collectCoverage": true,
    "testFileExtensions": [
      "js"
    ],
    "unmockedModulePathPatterns": [
      "promise",
      "source-map",
      "react",
      "jasmine-reporters"
    ]
  }
```

devDependencies:
```
    "jasmine-reporters": "^2.2.0",
    "jest-cli": "^0.9.0",
```

**Comment by MattFoley** [comment] 2016-06-22 16:51
After having this working for a few days, having to use sudo does seem like it's going to be problematic. So while you can use the above as a workaround, I don't think it's a good enough solution to close this issue. However, I'm also not sure whether this a mkdirp issue or a jasmine-reporters issue.

**Comment by bloveridge** [comment] 2016-06-22 19:35
It sounds like a permissions issue with how node is executed in general. If your filesystem doesn't allow the user node is running as to create the target directory (which using `sudo` bypasses), node isn't going to be able to create the directory whether you try via `mkdirp` or any other mechanism. 

You could look into changing the permissions of the parent directory to be writable by the user node runs as. You could also try any other mechanism to create the directory (such as using the native `fs` module, or trying `fs-extra` which has its own `mkdirp` equivalent). It sounds like a permissions issue that probably won't be satisfied by these other mechanisms, but if you find one that works I would be happy to change `jasmine-reporters` to use that new mechanism instead of `mkdirp`.

**Comment by MattFoley** [comment] 2016-06-22 20:14
@bloveridge I think you are correct. I think that the Jenkins user was unable to modify the files as they were created manually by running the tests myself on my build machine first. 

I added a step to my build script to manually delete the existing output scripts before running the tests each time, and it's all working for me now!

**Closed** 2016-06-22 20:52 UTC
